### ISSUE TITLE
setTimeout 里边使用 clearInterval 是失误吗

### ISSUE THREAD

**Issue by dragon8github** [jzfai/package-develop-template#1]
https://github.com/jzfai/package-develop-template/blob/9f85296fe9b9e622f374a5d2d88d376f097f2d42/packages/js-error-collection/index.js#L52

![image](https://user-images.githubusercontent.com/13919724/191469283-e7737cef-118f-458f-b542-d1f700743bd0.png)

另外延迟返回错误的优势是什么？

**Comment by jzfai** [comment]
通用写法喔
